models/alarmas.py
from utils.db import db
import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import smtplib
from config import MAILPASSW
from config import MAILADDR

class Alarmas(db.Model):

    id = db.Column(db.Integer, primary_key = True)
    cod_deposito = db.Column(db.String(255))
    cod_parte = db.Column(db.String(255))
    fecha = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    usuario = db.Column(db.String(255))
    mensaje = db.Column(db.String(255))
    estado = db.Column(db.String(255))

    #constructor
    def __init__(self, cod_deposito,cod_parte, usuario, mensaje,estado):
        self.cod_deposito=cod_deposito
        self.cod_parte=cod_parte
        self.usuario=usuario
        self.mensaje=mensaje
        self.estado=estado

    def to_json(self):
        return dict(
            id=self.id,
            cod_deposito=self.cod_deposito,
            cod_parte=self.cod_parte,
            usuario=self.usuario,
            fecha=self.fecha,
            mensaje=self.mensaje,
            estado=self.estado
            )

    def enviar_mail(self, mensaje, to_addr):
       print('enviar_mail')
       msg = MIMEMultipart()
       message = mensaje
 
       # setup the parameters of the message
       msg['From'] = "poaTP@up"
       msg['To'] = to_addr
       msg['Subject'] = "Alarma TP POA"
 
       # add in the message body
       msg.attach(MIMEText(message, 'plain'))
 
       #create server
       server = smtplib.SMTP('smtp.gmail.com')
 
       server.starttls()
 
       # Login Credentials for sending the mail
       print('antes login')
       server.login(MAILADDR,MAILPASSW)
       print('despues login')
       # send the message via the server.
       server.sendmail(msg['From'], msg['To'], msg.as_string())
       server.quit()
       print ("successfully sent email to %s:" % (msg['To']))


#crea todas las tablas de las clases
db.create_all

models/stock.py
from tkinter import Y
from utils.db import db
import datetime

class Stock(db.Model):

    id = db.Column(db.Integer, primary_key = True)
    cod_deposito = db.Column(db.String(255))
    cod_parte = db.Column(db.String(255))
    cantidad = db.Column(db.Float)
    capacidad_limite = db.Column(db.Float)

    #constructor
    def __init__(self, cod_deposito,cod_parte,cantidad, cap_lim):
        self.cod_deposito=cod_deposito
        self.cod_parte=cod_parte
        self.cantidad=cantidad
        self.capacidad_limite = cap_lim

    def to_json(self):
        return dict(
            id=self.id,
            cod_deposito=self.cod_deposito,
            cod_parte=self.cod_parte,
            cantidad=self.cantidad,
            capacidad_limite = self.capacidad_limite
            )

#crea todas las tablas de las clases
db.create_all

routes/alarmas.py
from email import utils
from flask import Blueprint, jsonify, render_template, request, redirect, url_for, flash
from utils.db import db
#importa la clase Alarmas
from models.alarmas import Alarmas
from flask_marshmallow import Marshmallow


#para separar en modulos las aplicaciones
alarmas = Blueprint('alarmas',__name__)


ma = Marshmallow(alarmas)

class AlarmasSchema(ma.Schema):
    class Meta:
        fields=('id', 'cod_deposito', 'cod_parte', 'usuario','mensaje','estado')

alarma_schema=AlarmasSchema()
alarma_schema=AlarmasSchema(many=True)

@alarmas.route('/alarmas', methods=["GET"])
def getAlarmas():
    obj = Alarmas.query.all()
    print(obj)
    return render_template('alarmas.html', alarmas = obj)
    
    
@alarmas.route('/alarmas', methods=['POST'])
def create_alarmas():
     cod_deposito = request.json['cod_deposito']
     cod_parte = request.json['cod_parte']
     usuario = request.json['usuario']
     mensaje = request.json['mensaje']
     estado = request.json['estado']
     new_object = Alarmas(cod_deposito, cod_parte, usuario, mensaje, estado)
     db.session.add(new_object)
     db.session.commit()
     return new_object.to_json()

@alarmas.route('/alarmas/<id>', methods=["GET"])
def get(id):
    qobj = Alarmas.query.get(id)
    return qobj.to_json()

@alarmas.route('/alarmas/<id>', methods=["POST"])
def update(id):
    qobj = Alarmas.query.get(id)
    estado = request.json['estado']
    qobj.estado = estado
    db.session.commit()
    return qobj.to_json()

routes/stock.py
from email import utils
from flask import Blueprint, jsonify, render_template, request, redirect, url_for, flash
from utils.db import db
from models.stock import Stock
from sqlalchemy import func, text, select, and_, join

#para separar en modulos las aplicaciones
stock = Blueprint('stock',__name__)


@stock.route('/stock', methods=["GET"])
def getStock():
    #stk = Stock.query.all()
    stmt = select([Stock.id, Stock.cod_deposito, Stock.cod_parte, Stock.cantidad, Stock.capacidad_limite, ((Stock.cantidad / Stock.capacidad_limite) * 100 ).label('capacidad_actual')])
    stock_result = db.session.execute(stmt).fetchall()
    print(stock_result)
    return render_template('stock.html', stock = stock_result)

    
    
    
@stock.route('/stock', methods=['POST'])
def create():
     cod_deposito,cod_parte,cantidad, cap_lim
     cod_deposito = request.json['cod_deposito']
     cod_parte = request.json['cod_parte']
     cantidad = request.json['cantidad']
     cap_lim = request.json['cap_lim']
     new_object = Stock(cod_deposito, cod_parte, cantidad, cap_lim)
     db.session.add(new_object)
     db.session.commit()
     return new_object.to_json()

@stock.route('/stock/<id>', methods=["GET"])
def get(id):
    qobj = Stock.query.get(id)
    return qobj.to_json()

@stock.route('/stock/<id>', methods=["POST"])
def update(id):
    qobj = Stock.query.get(id)
    cantidad = request.json['cantidad']
    qobj.cantidad = cantidad
    db.session.commit()
    return qobj.to_json()

routes/transacciones.py
from doctest import Example
from email import utils
from flask import Blueprint, render_template, request, redirect, url_for, flash
from utils.db import db
#importa la clase Transacciones
from models.transacciones import Transacciones
from models.stock import Stock
from models.alarmas import Alarmas
from models.usuarios import Usuarios
from models.roles import Roles
from models.partes import Partes
from models.tipo_partes import Tipo_partes
from sqlalchemy import text, select, and_, join
import logging
from flask_login import LoginManager, login_user, logout_user, login_required
from sqlalchemy_paginator import Paginator

#para separar en modulos las aplicaciones
transacciones = Blueprint('transacciones',__name__)



@transacciones.route("/home")
#@login_required
def home():
    print('transacciones.home')
    trxs = Transacciones.query.all()
    return render_template('index.html', transacciones = trxs)


@transacciones.route('/transacciones', methods=['POST'])
def create_transacciones():
     tipo = request.form['tipo']
     cod_deposito = request.form['cod_deposito']
     cod_labo = request.form['cod_labo']
     cod_parte = request.form['cod_parte']
     cantidad = request.form['cantidad']
     cantidad_des = 0
     cantidad_util = 0
     
     if tipo == "EGR":
       print('EGRESO')
       #validar egreso de stock --. 
       stmt = select([Stock.id]).where(and_(Stock.cod_deposito == cod_deposito,
                                          Stock.cod_parte == cod_parte
                                          ))
       stock_result = db.session.execute(stmt).fetchall()
       if not stock_result:
          print('result query is empty')
          flash("No hay stock para egresos")    
       else:   
           #--actualizar_stock--
           print(stock_result)
           resultx = [r[0] for r in stock_result]
           idStock = resultx[0]
           print(idStock)
           stock_obj = Stock.query.get(idStock)
           if stock_obj.cantidad >= float(cantidad):
              stock_obj.cantidad = float(stock_obj.cantidad) -  float(cantidad)
              print('stock actualizado')
              #ingresar_trx
              new_transaccion = Transacciones(tipo, cod_deposito, cod_labo, cod_parte, cantidad, cantidad_des, cantidad_util)
              db.session.add(new_transaccion)
              db.session.commit()
              flash("Transaccion de EGRESO creada exitosamente")
              print('trx creada')
             
              #--check_alarma----
              #obtener del tipo de pieza el porcentaje limite
              stmt = select([Tipo_partes.porc_limite]).join(Partes, Partes.tipo_parte_id == Tipo_partes.id).where(Partes.cod_parte == cod_parte)

              p_result = db.session.execute(stmt).fetchall()
              if not p_result:
                print('tipo parte query is empty')
                flash("tipo parte no enconetrada")    
              else:   
                #--verificar porc limite
                print(p_result)
                resultx = [r[0] for r in p_result]
                porc_lim_r = resultx[0]
                print('porc limi parte')
                print(porc_lim_r)
                print('obteniendo porc actual parte en deposito: ')
                print('stock actual')
                print(stock_obj.cantidad)
                print('capacidad limite: ') 
                print(stock_obj.capacidad_limite)
                print('calculando porc_act ')
                porc_act = (float(stock_obj.cantidad) / float(stock_obj.capacidad_limite)) * 100
                print(porc_act)

                if float(porc_act) < float(porc_lim_r):
                #COMENTADO EL IF PARA QUE ENTRE EN ESTA PARTE Y PROBAR ENVIO DE ALARMAS!!!!!!!!!!!!
                #if 1==1:
                  #crear alarma         
                  print('crear alarma')
                  print('obteniendo usuarios')

                  stmt = select([Usuarios.email, Usuarios.codigo, Usuarios.nombre]).join(Roles, Usuarios.rol_id == Roles.id).where(Roles.codigo == "SUPERVISOR")
                  usuarios_alarmas = db.session.execute(stmt).fetchall()
                  if not usuarios_alarmas:
                    print('roles usuarios query is empty')
                    flash("usuarios supervisores no enconetrados")    
                  else:   
                    #--verificar porc limite
                    print(usuarios_alarmas)

                    for r in usuarios_alarmas:
                       email_usuario=r[0]
                       print(email_usuario)
                       cod_usuario = r[1]
                       print(cod_usuario)
                       nombre_usuario = r[2]
                       print(nombre_usuario)
                       #enviar_alarma()
                       mensaje = ('Hola '+nombre_usuario+': El stock para el DEPOSITO: ' + cod_deposito + ' , PARTE: ' + cod_parte + 
                              ' esta por debajo del PORC. LIMITE. Por favor, realizar las acciones correspondientes.' )
                       new_alarma = Alarmas(cod_deposito,cod_parte,cod_usuario, mensaje, "PENDIENTE")
                       try:
                         new_alarma.enviar_mail(mensaje, email_usuario)
                         new_alarma.estado='ENVIADA'
                         db.session.add(new_alarma)
                         db.session.commit()
                         print("enviar alarma")   
                       except Exception as ex:
                        print('error envio mail')
                        print (ex)
                        

           else:
             flash("Cantidad en Stock insuficiente. Transaccion de EGRESO no creada.")     

     else:
       print('INGRESO')
       logging.warning("INGRESO proceso....")
       #trx de INGRESO
       #actualizar stock
       stmt = select([Stock.id]).where(and_(Stock.cod_deposito == cod_deposito,
                                          Stock.cod_parte == cod_parte
                                          ))
       stock_result = db.session.execute(stmt).fetchall()
       
       if not stock_result:
          print('result query stock is empty')
          flash("No hay stock para egresos")    
       else:
          print(stock_result)
          resultx = [r[0] for r in stock_result]
          idStock = resultx[0]
          print(idStock)
          stock_obj = Stock.query.get(idStock)
          stock_obj.cantidad = float(stock_obj.cantidad) +  float(cantidad)
       new_transaccion = Transacciones(tipo, cod_deposito, cod_labo, cod_parte, cantidad, cantidad_des, cantidad_util)
       db.session.add(new_transaccion)
       db.session.commit()
       flash("Transaccion de INGRESO creada exitosamente")
     return redirect(url_for("transacciones.home"))



@transacciones.route('/update/<id>', methods=["GET","POST"])
def update(id):
    q_trx = Transacciones.query.get(id)
    if request.method=="POST":
      q_trx.cantidad_des = request.form["cantidad_des"]
      q_trx.cantidad_util = request.form["cantidad_util"]
      #validar cantidad_des + cantidad_util = cantidad
      db.session.commit()
      flash("Transaccion actualizada exitosamente")
      return redirect(url_for("transacciones.home"))
    return render_template('edit_trx.html', trx = q_trx)


#@API con paginacion
@transacciones.route('/reporte', methods=['GET','POST'], defaults={"page": 1}) 
@transacciones.route('/reporte/<int:page>', methods=['GET', 'POST'])
def reporte(page):
    print('transacciones.route ')
    print(page)
    page = int(page)
    per_page = 5
    
    #trxs = Transacciones.query.all()
    trxs = Transacciones.query.paginate(page,per_page,max_per_page=10,error_out=False)

    return render_template('reporte.html', transacciones = trxs)

templates/alarmas.html
{% extends 'layout.html' %}
{% block body %}

<h1>Alarmas</h1>
<div class="row">
    <div class="col-md-7" offset-md-2>
        <table class=" table table-striped table-bordered bg-white table-sm">
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Deposito</td>
                    <td>Parte</td>
                    <td>Fecha</td>
                    <td>Usuario</td>
                    <td>Mensaje</td>
                    <td>Estado</td>
                </tr>
            </thead>
            <tbody>

                {% for alm in alarmas %}
                <tr>
                    <td>{{alm.id}}</td>
                    <td>{{alm.cod_deposito}}</td>
                    <td>{{alm.cod_parte}}</td>
                    <td>{{alm.fecha}}</td>
                    <td>{{alm.usuario}}</td>
                    <td>{{alm.mensaje}}</td>
                    <td>{{alm.estado}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>


    </div>

</div>

{% endblock %}

templates/edit_trx.html
{% extends 'layout.html' %}
{% block body %}

<div class="col-md-7 offset-md-2"> 
    <div class="card card-body">
        <form action="/update/{{trx.id}}" method="POST">
            <div class="form-group">
                <label for="id">ID</label>
                <input type="text" id="id" name="ID" placeholder="ID" value="{{trx.id}}" class="form-control" readonly>
            </div>
            <div class="form-group">
                <label for="tipo">Tipo</label>
                <input type="tipo" name="tipo" placeholder="Tipo" value="{{trx.tipo}}" class="form-control" readonly >
            </div>
            <div class="form-group">
                <label for="fecha">Fecha</label>
                <input type="text" name="fecha" placeholder="Fecha" value="{{trx.fecha}}" class="form-control" readonly>
            </div>

            <div class="form-group">
                <label for="cod_deposito">Deposito</label>
                <input type="text" name="cod_deposito" placeholder="Deposito" value="{{trx.cod_deposito}}" class="form-control" readonly>
            </div>
            <div class="form-group">
                <label for="cod_labo">Laboratorio</label>
                <input type="text" name="cod_labo" placeholder="Laboratorio" value="{{trx.cod_labo}}" class="form-control" readonly>
            </div>
            <div class="form-group">
                <label for="cod_parte">Parte</label>
                <input type="text" name="cod_parte" placeholder="Parte" value="{{trx.cod_parte}}" class="form-control" readonly>
            </div> 
            <div class="form-group">
                <label for="cantidad">Cantidad</label>
                <input type="text" name="cantidad" placeholder="Cantidad" value="{{trx.cantidad}}" class="form-control" readonly>
            </div> 
            <div class="form-group">
                <label for="cantidad_des">Cant. Desechada</label>
                <input type="text" name="cantidad_des" placeholder="Cant. Desechada" value="{{trx.cantidad_des}}" class="form-control">
            </div> 
            <div class="form-group">
                <label for="cantidad_util">Cant. Utilizada</label>
                <input type="text" name="cantidad_util" placeholder="Cant. Utilizada" value="{{trx.cantidad_util}}" class="form-control">
            </div> 

            <div class="form-group">
                <button type="submit" class="btn btn-success btn-block">  Guardar </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% block body %}
<h1>Transacciones</h1>
<div class="row">


    <div class="col-md-5" offset-md-2>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <div class="card card-body">
            <form action="/transacciones" method="POST">
                <div class="form-group">
                    <input type="text" name="tipo" placeholder="Tipo" class="form-control">
                </div>
                <div class="form-group">
                    <input type="text" name="cod_deposito" placeholder="Deposito" class="form-control">
                </div>
                <div class="form-group">
                    <input type="text" name="cod_labo" placeholder="Laboratorio" class="form-control">
                </div>
                <div class="form-group">
                    <input type="text" name="cod_parte" placeholder="Parte" class="form-control">
                </div>
                <div class="form-group">
                    <input type="text" name="cantidad" placeholder="Cantidad" class="form-control">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Guardar </button>
                </div>
            </form>
        </div>

    </div>
    
    <div class="col-md-7" offset-md-2>
            <table class=" table table-striped table-bordered bg-white table-sm">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>Tipo</td>
                        <td>Fecha</td>
                        <td>Deposito</td>
                        <td>Laboratorio</td>
                        <td>Pieza</td>
                        <td>Cantidad</td>
                        <td>Cantidad Descarte</td>
                        <td>Cantidad Utilizada</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    {% for trx in transacciones %}
                    <tr>
                        <td>{{trx.id}}</td>
                        <td>{{trx.tipo}}</td>
                        <td>{{trx.fecha}}</td>
                        <td>{{trx.cod_deposito}}</td>
                        <td>{{trx.cod_labo}}</td>
                        <td>{{trx.cod_parte}}</td>
                        <td>{{trx.cantidad}}</td>
                        <td>{{trx.cantidad_des}}</td>
                        <td>{{trx.cantidad_util}}</td>
                        <td>
                            <a href="{{url_for('transacciones.update', id= trx.id)}}" class="btn btn-secondary">Editar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
    </div>

</div>



{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>POA TP app</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/cerulean/bootstrap.min.css"
        integrity="sha384-3fdgwJw17Bi87e1QQ4fsLn4rUFqWw//KU0g8TvV6quvahISRewev6/EocKNuJmEw" crossorigin="anonymous">
</head>

<body>

    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{url_for('transacciones.home')}}">Transacciones</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('transacciones.reporte', pagenumber=1)}}">Reporte</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('stock.getStock')}}">Stock</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('alarmas.getAlarmas')}}">Alarmas</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" pt-4>
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
        integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
        integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
        crossorigin="anonymous"></script>
</body>

</html>

templates/login_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <!--Boostrapt-->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="icon" href="../../favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.3/examples/signin/">

    <!--custom css-->
    {% block customCSS %}
    {% endblock %}
</head>

<body class="text-center">
    {% block body %}
    {% endblock %}
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</body>

</html>

templates/reporte.html
{% extends 'layout.html' %}
{% block body %}


<h1>Reporte</h1>
<div class="row">

    <div class="col-md-7" offset-md-2>
        <table class=" table table-striped table-bordered bg-white table-sm">
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Tipo</td>
                    <td>Fecha</td>
                    <td>Deposito</td>
                    <td>Laboratorio</td>
                    <td>Pieza</td>
                    <td>Cantidad</td>
                    <td>Cantidad Descarte</td>
                    <td>Cantidad Utilizada</td>
                </tr>
            </thead>
            <tbody>

                {% for trx in transacciones.items %}
                <tr>
                    <td>{{trx.id}}</td>
                    <td>{{trx.tipo}}</td>
                    <td>{{trx.fecha}}</td>
                    <td>{{trx.cod_deposito}}</td>
                    <td>{{trx.cod_labo}}</td>
                    <td>{{trx.cod_parte}}</td>
                    <td>{{trx.cantidad}}</td>
                    <td>{{trx.cantidad_des}}</td>
                    <td>{{trx.cantidad_util}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>


        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if transacciones.has_prev %}
                <li class="page-item"> <a class="page-link"
                        href="{{ url_for('transacciones.reporte', page=transacciones.prev_num) }}">Previous</a></li>
                {% else %}
                <li class="page-item"><a class="page-link btn disabled" href="#">Previous</a></li>
                {% endif %}



                {% for page in transacciones.iter_pages(left_edge=3, right_edge=3) %}
                {% if page %}

                {% if page==transacciones.page %}
                <li class="page-item active"><a class="page-link" href="{{ url_for('transacciones.reporte', page=page) }}">{{ page
                        }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="{{ url_for('transacciones.reporte', page=page) }}">{{ page }}</a></li>
                {% endif %}

                {% else %}
                <li class="page-item disabled" id="example_ellipsis"><a href="#" class="page-link">…</a></li>
                {% endif %}
                {% endfor %}

                {% if transacciones.has_next %}
                <li class="page-item"> <a class="page-link"
                        href="{{ url_for('transacciones.reporte', page=transacciones.next_num) }}">Next</a></li>
                {% else %}
                <li class="page-item"><a class="page-link btn disabled" href="#">Next</a></li>
                {% endif %}
            </ul>
        </nav>





    </div>

</div>

{% endblock %}

templates/stock.html
{% extends 'layout.html' %}
{% block body %}

<h1>Stock </h1>
<div class="row">
    <div class="col-md-7" offset-md-2>
        <table class=" table table-striped table-bordered bg-white table-sm">
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Deposito</td>
                    <td>Parte</td>
                    <td>Cantidad</td>
                    <td>CapacidadLimiteDeposito</td>
                    <td>% CapacidadActual</td>
                </tr>
            </thead>
            <tbody>

                {% for stk in stock %}
                <tr>
                    <td>{{stk.id}}</td>
                    <td>{{stk.cod_deposito}}</td>
                    <td>{{stk.cod_parte}}</td>
                    <td>{{stk.cantidad}}</td>
                    <td>{{stk.capacidad_limite}}</td>
                    <td>{{stk.capacidad_actual}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>


    </div>

</div>

{% endblock %}